spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/academia}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:33forever}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    default-property-inclusion: non_null

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:minha-chave-secreta-academia-muito-segura-2024-deve-ter-256-bits}
    expiration: 86400000 # 24 horas em ms

  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
